### ISSUE TITLE
end button

### ISSUE THREAD

**Issue by Yvonne0904** [Losiyu/anno-tool#4]
It will be better if there are also buttons for reaching the end time.

**Comment by LaskySY** [comment]
Can I know how you going use this function and why it is important?

**Comment by Yvonne0904** [comment]
> Can I know how you going use this function and why it is important?

To check whether the end time is accurate.

**Comment by LaskySY** [comment]
In the last commit, I deploy a feature of stopping the video at the end time. Can you have a check if it is satisfy yout requirement?
Detail:
After click the index button in the annotation table, the video will start at the row 'Start' time and pause at the row 'End' time.
